using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using VertexERP.Controllers;
using VertexERP.Data;
using VertexERP.Models;
using VertexERP.Services;

void Check(bool result, string name) { if (!result) throw new Exception(name); Console.WriteLine("PASS: " + name); }
using var db = new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>().UseNpgsql("Host=localhost;Database=unused").Options);
var actor = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.NameIdentifier, "42"), new Claim(ClaimTypes.Name, "Manager Test"), new Claim(ClaimTypes.Role, "Manager") }, "test"));
var task = new WorkTask { Id = 12, Title = "Prepare report", ManagerId = 1, AssigneeId = 2 };
db.Add(task);
var log = AuditLogFactory.Create(db.Entry(task), actor)!;
Check(log.Action == "Task assigned" && log.ActorId == "42" && log.Detail.Contains("employee #2"), "Task assignment records actor and assignee");
db.Entry(task).State = EntityState.Unchanged;
task.Status = "In Progress";
db.ChangeTracker.DetectChanges();
log = AuditLogFactory.Create(db.Entry(task), actor)!;
Check(log.Action == "Task status changed" && log.Detail.Contains("To Do → In Progress"), "Status history preserves old and new values");
db.Entry(task).State = EntityState.Unchanged;
task.AssigneeId = 3;
db.ChangeTracker.DetectChanges();
Check(AuditLogFactory.Create(db.Entry(task), actor)!.Detail.Contains("employee #2 → #3"), "Reassignment identifies both assignees");
db.Entry(task).State = EntityState.Unchanged;
Check(AuditLogFactory.Create(db.Entry(task), actor) == null, "Reads do not create activity");
var audit = new AuditLog(); db.Add(audit);
Check(AuditLogFactory.Create(db.Entry(audit), actor) == null, "Audit entries do not recursively audit themselves");
db.Entry(task).State = EntityState.Deleted;
Check(AuditLogFactory.Create(db.Entry(task), null)!.ActorName == "System", "Background changes have a system actor");
var access = (AuthorizeAttribute)Attribute.GetCustomAttribute(typeof(AuditController), typeof(AuthorizeAttribute))!;
Check(access.Roles == "Admin", "Audit page and live endpoint require Admin");
Check(db.Model.FindEntityType(typeof(AuditLog)) != null, "Audit history is included in database model");
var auditController = new AuditController(db);
Check(await auditController.Delete(null, null, null, 0, default) is Microsoft.AspNetCore.Mvc.BadRequestObjectResult, "Unbounded bulk deletion is rejected");
Check(await auditController.Delete(null, new DateOnly(2026, 9, 15), new DateOnly(2026, 9, 14), 1, default) is Microsoft.AspNetCore.Mvc.BadRequestObjectResult, "Reversed deletion dates are rejected");
Check(await auditController.Download(new DateOnly(2026, 9, 15), new DateOnly(2026, 9, 14), default) is Microsoft.AspNetCore.Mvc.BadRequestObjectResult, "PDF rejects reversed dates");
var deleteMethod = typeof(AuditController).GetMethod("Delete")!;
Check(Attribute.IsDefined(deleteMethod, typeof(Microsoft.AspNetCore.Mvc.HttpPostAttribute)) && Attribute.IsDefined(deleteMethod, typeof(Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute)), "Deletion requires POST and anti-forgery validation");
var deleteAllMethod = typeof(AuditController).GetMethod("DeleteAll")!;
Check(Attribute.IsDefined(deleteAllMethod, typeof(Microsoft.AspNetCore.Mvc.HttpPostAttribute)) && Attribute.IsDefined(deleteAllMethod, typeof(Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute)), "Delete All requires POST and anti-forgery validation");
