using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Vertex_ERP.Migrations
{
    /// <inheritdoc />
    public partial class AddEmployeeManagement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $migration$
                BEGIN
                    IF to_regclass('public."Employees"') IS NULL THEN
                        CREATE TABLE "Employees" (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                            "EmployeeCode" character varying(30) NOT NULL,
                            "FirstName" character varying(60) NOT NULL,
                            "LastName" character varying(60) NOT NULL,
                            "FullName" character varying(120) NOT NULL,
                            "Email" character varying(150) NOT NULL,
                            "PhoneNumber" character varying(20) NOT NULL,
                            "DateOfBirth" date NULL,
                            "Gender" character varying(20) NULL,
                            "Address" character varying(300) NULL,
                            "City" character varying(80) NULL,
                            "State" character varying(80) NULL,
                            "JoiningDate" date NOT NULL,
                            "Department" character varying(80) NOT NULL,
                            "Designation" character varying(80) NOT NULL,
                            "ReportingManagerId" integer NULL,
                            "EmploymentType" character varying(30) NOT NULL,
                            "EmployeeStatus" character varying(30) NOT NULL,
                            "IsActive" boolean NOT NULL,
                            "CreatedDate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            "UpdatedDate" timestamp with time zone NULL,
                            CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
                            CONSTRAINT "FK_Employees_Employees_ReportingManagerId"
                                FOREIGN KEY ("ReportingManagerId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT
                        );
                    ELSE
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "FirstName" character varying(60);
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "LastName" character varying(60);
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "Address" character varying(300);
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "City" character varying(80);
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "State" character varying(80);
                        ALTER TABLE "Employees" ADD COLUMN IF NOT EXISTS "EmployeeStatus" character varying(30);

                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'OfficialEmail')
                           AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'Email') THEN
                            ALTER TABLE "Employees" RENAME COLUMN "OfficialEmail" TO "Email";
                        END IF;
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'MobileNumber')
                           AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'PhoneNumber') THEN
                            ALTER TABLE "Employees" RENAME COLUMN "MobileNumber" TO "PhoneNumber";
                        END IF;
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'CreatedAt')
                           AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Employees' AND column_name = 'CreatedDate') THEN
                            ALTER TABLE "Employees" RENAME COLUMN "CreatedAt" TO "CreatedDate";
                        END IF;

                        UPDATE "Employees"
                        SET "FirstName" = COALESCE("FirstName", CASE WHEN position(' ' IN trim("FullName")) > 0 THEN split_part(trim("FullName"), ' ', 1) ELSE trim("FullName") END),
                            "LastName" = COALESCE("LastName", CASE WHEN position(' ' IN trim("FullName")) > 0 THEN substr(trim("FullName"), position(' ' IN trim("FullName")) + 1) ELSE '-' END),
                            "EmployeeStatus" = COALESCE("EmployeeStatus", CASE WHEN "IsActive" THEN 'Active' ELSE 'Inactive' END);

                        ALTER TABLE "Employees" ALTER COLUMN "FirstName" SET NOT NULL;
                        ALTER TABLE "Employees" ALTER COLUMN "LastName" SET NOT NULL;
                        ALTER TABLE "Employees" ALTER COLUMN "EmployeeStatus" SET NOT NULL;

                        IF to_regclass('public."IX_Employees_OfficialEmail"') IS NOT NULL
                           AND to_regclass('public."IX_Employees_Email"') IS NULL THEN
                            ALTER INDEX "IX_Employees_OfficialEmail" RENAME TO "IX_Employees_Email";
                        END IF;
                    END IF;
                END $migration$;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Employees_Email" ON "Employees" ("Email");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Employees_EmployeeCode" ON "Employees" ("EmployeeCode");
                CREATE INDEX IF NOT EXISTS "IX_Employees_ReportingManagerId" ON "Employees" ("ReportingManagerId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Employees");
        }
    }
}
